### ISSUE TITLE
Unable to proceed to bwa step

### ISSUE THREAD

**Issue by J8git** [nf-core/atacseq#185]
Fastqc and Trimgalore works perfectly. However I have not been able to proceed to bwa step, even after I upgraded from 22.04.0 version to 22.08.0-edge nextflow version.

Here is the error message:

Aug-10 00:43:02.549 [Actor Thread 73] ERROR nextflow.processor.TaskProcessor - Error executing process > 'BWA_MEM (CON_R2_T1)'

Caused by:
  Not a valid S3 file system provider file attribute view: java.nio.file.attribute.BasicWithKeyFileAttributeView

java.lang.UnsupportedOperationException: Not a valid S3 file system provider file attribute view: java.nio.file.attribute.BasicWithKeyFileAttributeView
	at com.upplication.s3fs.S3FileSystemProvider.getFileAttributeView(S3FileSystemProvider.java:733)
	at java.base/java.nio.file.Files.getFileAttributeView(Files.java:1776)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:221)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:282)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:328)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2792)
	at com.upplication.s3fs.AmazonS3Client.downloadDirectory(AmazonS3Client.java:547)
	at com.upplication.s3fs.S3FileSystemProvider.download(S3FileSystemProvider.java:366)
	at nextflow.file.FileHelper.copyPath(FileHelper.groovy:940)
	at nextflow.file.FilePorter$FileTransfer.stageForeignFile0(FilePorter.groovy:294)
	at nextflow.file.FilePorter$FileTransfer.stageForeignFile(FilePorter.groovy:261)
	at nextflow.file.FilePorter$FileTransfer.run(FilePorter.groovy:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Aug-10 00:43:02.558 [Actor Thread 73] DEBUG nextflow.Session - Session aborted -- Cause: Not a valid S3 file system provider file attribute view: java.nio.file.attribute.BasicWithKeyFileAttributeView

I have been stuck at this for a long time. Using -profile singularity and have wrote in nextflow.config to use downloaded  "nf-core-atacseq-1.2.2.simg" container instead.  Did not change the rest of the script in nextflow.config.

How can this be solved? Thank you!

**Comment by JoseEspinosa** [comment]
Which command have you used to run the pipeline?

**Comment by drpatelh** [comment]
Hi @J8git ! Thanks for reporting! We are about to release a much updated version of the pipeline that has been completely refactored to be written in Nextflow DSL2. When this is released, it would be great if you can let us know if the problem still persists. I will close this issue for now.

For faster, real-time help for these sorts of things please join the #atacseq channel on the nf-core Slack workspace. You can join via the link below:
https://nf-co.re/join
