### ISSUE TITLE
multiqc failed with error message below

### ISSUE THREAD

**Issue by jianxinwang** [nf-core/atacseq#205]
```
Command error:
  [INFO   ]          fastqc : Found 22 reports
  [INFO   ]        cutadapt : Found 22 reports
  [INFO   ]          fastqc : Found 22 reports
  [INFO   ]        samtools : Found 11 stats reports
  [INFO   ]        samtools : Found 11 flagstat reports
  [INFO   ]        samtools : Found 11 idxstats reports
  [INFO   ]        samtools : Found 11 stats reports
  [INFO   ]        samtools : Found 11 flagstat reports
  [INFO   ]        samtools : Found 11 idxstats reports
  [INFO   ]          preseq : Found 11 reports
  [INFO   ]        samtools : Found 11 stats reports
  [INFO   ]        samtools : Found 11 flagstat reports
  [INFO   ]        samtools : Found 11 idxstats reports
  [INFO   ]          picard : Found 11 AlignmentSummaryMetrics reports
  [INFO   ]          picard : Found 22 BaseDistributionByCycleMetrics reports
  [INFO   ]          picard : Found 11 InsertSizeMetrics reports
  [INFO   ]          picard : Found 11 MarkDuplicates reports
  [INFO   ]          picard : Found 11 QualityByCycleMetrics reports
  [INFO   ]          picard : Found 11 QualityScoreDistributionMetrics reports
  [INFO   ]       deeptools : Found 22 total deepTools samples
  [INFO   ]  feature_counts : Found 11 reports
  [INFO   ]        samtools : Found 4 stats reports
  [INFO   ]        samtools : Found 4 flagstat reports
  [INFO   ]        samtools : Found 4 idxstats reports
  [ERROR  ]         multiqc : Oops! The 'picard' MultiQC module broke... 
    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
    If possible, please include a log file that triggers the error - the last file found was:
      ./alignment/mergedReplicate/519RBDCDKminusDOX.mRp.clN.MarkDuplicates.metrics.txt
 
  Module picard raised an exception: Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-atacseq-1.2.2/lib/python3.7/site-packages/multiqc/modules/picard/MarkDuplicates.py", line 137, in parse_reports
      parsed_data[k] += float(vals[i])
  ValueError: could not convert string to float: 
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-atacseq-1.2.2/lib/python3.7/site-packages/multiqc/multiqc.py", line 569, in run
      output = mod()
    File "/opt/conda/envs/nf-core-atacseq-1.2.2/lib/python3.7/site-packages/multiqc/modules/picard/picard.py", line 73, in __init__
      n['MarkDuplicates'] = MarkDuplicates.parse_reports(self)
    File "/opt/conda/envs/nf-core-atacseq-1.2.2/lib/python3.7/site-packages/multiqc/modules/picard/MarkDuplicates.py", line 139, in parse_reports
      parsed_data[k] += " / " + vals[i]
  TypeError: unsupported operand type(s) for +=: 'float' and 'str'

  [INFO   ]  feature_counts : Found 11 reports
  [INFO   ]         multiqc : Compressing plot data
  [INFO   ]         multiqc : Report      : multiqc_report.html
  [INFO   ]         multiqc : Data        : multiqc_data
  [INFO   ]         multiqc : MultiQC complete
```

**Comment by ewels** [comment]
Please attach the mentioned file `519RBDCDKminusDOX.mRp.clN.MarkDuplicates.metrics.txt` so that we can test and replicate the error.

**Comment by drpatelh** [comment]
Hi @jianxinwang ! Thanks for reporting! We are about to release a much updated version of the pipeline that has been completely refactored to be written in Nextflow DSL2. When this is released, it would be great if you can let us know if the problem still persists and attach the requested files as well as the (redacted) `.nextflow.log`. I will close this issue for now.
