### ISSUE TITLE
NameError: name 'logger' is not defined

### ISSUE THREAD

**Issue by kokyriakidis** [nf-core/atacseq#263]
Hey!

I get the following error trying to run this pipeline with the test and conda profile on my MacOS X86

```
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/atacseq] Pipeline completed with errors-
Error executing process > 'NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_ATAQV_MKARV'

Caused by:
  Process `NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_ATAQV_MKARV` terminated with an error exit status (1)

Command executed:

  mkarv \
       \
      --concurrency 2 \
      --force \
      ./html/ \
      OSMOTIC_STRESS_T100_SE_REP1.ataqv.json OSMOTIC_STRESS_T100_SE_REP2.ataqv.json OSMOTIC_STRESS_T150_SE_REP1.ataqv.json OSMOTIC_STRESS_T0_PE_REP2.ataqv.json OSMOTIC_STRESS_T0_PE_REP1.ataqv.json OSMOTIC_STRESS_T15_PE_REP1.ataqv.json

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_ATAQV_MKARV":
      # mkarv: $( mkarv --version ) # Use this when version string has been fixed
      ataqv: $( ataqv --version )
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Using 2 concurrent processes to transform ataqv output files
  Copying web visualizer template directory /Users/kokyriakidis/Downloads/work/conda/env-5a07b4ddb6885bc08bfcbb858b46efee/web to ./html/
  Creating data directory ./html/data
  multiprocessing.pool.RemoteTraceback:
  """
  Traceback (most recent call last):
    File "/Users/kokyriakidis/Downloads/work/conda/env-5a07b4ddb6885bc08bfcbb858b46efee/lib/python3.10/multiprocessing/pool.py", line 125, in worker
      result = (True, func(*args, **kwds))
    File "/Users/kokyriakidis/Downloads/work/conda/env-5a07b4ddb6885bc08bfcbb858b46efee/bin/mkarv", line 532, in load_metrics
      logger.info('Adding metrics file {}'.format(metrics_filename))
  NameError: name 'logger' is not defined
  """

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/Users/kokyriakidis/Downloads/work/conda/env-5a07b4ddb6885bc08bfcbb858b46efee/bin/mkarv", line 611, in <module>
      for metrics_list in loaded_metrics:
    File "/Users/kokyriakidis/Downloads/work/conda/env-5a07b4ddb6885bc08bfcbb858b46efee/lib/python3.10/multiprocessing/pool.py", line 873, in next
      raise value
  NameError: name 'logger' is not defined

Work dir:
  /Users/kokyriakidis/Downloads/work/47/755b537df57350a41b8c79b5e66a84

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

I am not sure why it cannot find "logger". Any clue?

**Comment by JoseEspinosa** [comment]
Not sure what the source of the error could be. Anyhow the recommendation will be to use Docker or Singularity to run the pipeline, if is available in your system since those are the best and easiest.

**Comment by cloudwolf516** [comment]
I'm getting the same error as well using conda. In reviewing the mkarv script it appears to "import logging", but utilize the "logger" package on line 532. Not sure if that is intended in this case.

https://github.com/ParkerLab/ataqv/blob/master/src/scripts/mkarv

**Comment by JoseEspinosa** [comment]
If it is a problem with conda resolving dependencies, as it seems, it might be worth trying the `dev` version of the pipeline since `markv` and `ataqv` have been updated to version 1.3.1.
