### ISSUE TITLE
Process `NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_ATAQV_MKARV` terminated with an error exit status (1)

### ISSUE THREAD

**Issue by kkim111** [nf-core/atacseq#302]
### Description of the bug

Hi,
I am a beginner and I have a problem with running the pipeline.

My full command was:
nextflow run nf-core/atacseq --input design.csv --outdir 01_nextflow_output/ --genome mm10 -profile singularity --read_length 150 --macs_gsize 3000000000

Would you please explain what is wrong and how I can solve this problem?
Thank you very much.

### Command used and terminal output

```console
Error executing process > 'NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_ATAQV_MKARV'

Caused by:
  Process `NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_ATAQV_MKARV` terminated with an error exit status (1)

Command executed:

  mkarv \
       \
      --concurrency 6 \
      --force \
      ./html/ \
      control_REP2.ataqv.json control_REP3.ataqv.json treatment_REP2.ataqv.json treatment_REP1.ataqv.json treatment_REP3.ataqv.json control_REP1.ataqv.json
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_ATAQV_MKARV":
      # mkarv: $( mkarv --version ) # Use this when version string has been fixed
      ataqv: $( ataqv --version )
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Using 6 concurrent processes to transform ataqv output files
  Copying web visualizer template directory /usr/local/web to ./html/
  Traceback (most recent call last):
    File "/usr/local/bin/mkarv", line 600, in 
      shutil.copytree(args.template_directory, args.directory)
    File "/usr/local/lib/python3.9/shutil.py", line 566, in copytree
      return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
    File "/usr/local/lib/python3.9/shutil.py", line 522, in _copytree
      raise Error(errors)
  shutil.Error: [('/usr/local/web/css/ataqv.css', './html/css/ataqv.css', '[Errno 1] Operation not permitted'), ('/usr/local/web/css/datatables.buttons.min.css', './html/css/datatables.buttons.min.css', '[Errno 1] Operation not permitted'), ('/usr/local/web/css/datatables.fontawesome.css', './html/css/datatables.fontawesome.css', '[Errno 1] Operation not permitted'), ('/usr/local/web/css/datatables.min.css', './html/css/datatables.min.css', '[Errno 1] Operation not permitted'), ('/usr/local/web/css/font-awesome.min.css', './html/css/font-awesome.min.css', '[Errno 1] Operation not permitted'), ('/usr/local/web/css/normalize.css', './html/css/normalize.css', '[Errno 1] Operation not permitted'), (, './html/css', '[Errno 1] Operation not permitted'), ('/usr/local/web/fonts/FontAwesome.otf', './html/fonts/FontAwesome.otf', '[Errno 1] Operation not permitted'), ('/usr/local/web/fonts/fontawesome-webfont.eot', './html/fonts/fontawesome-webfont.eot', '[Errno 1] Operation not permitted'), ('/usr/local/web/fonts/fontawesome-webfont.svg', './html/fonts/fontawesome-webfont.svg', '[Errno 1] Operation not permitted'), ('/usr/local/web/fonts/fontawesome-webfont.ttf', './html/fonts/fontawesome-webfont.ttf', '[Errno 1] Operation not permitted'), ('/usr/local/web/fonts/fontawesome-webfont.woff', './html/fonts/fontawesome-webfont.woff', '[Errno 1] Operation not permitted'), ('/usr/local/web/fonts/fontawesome-webfont.woff2', './html/fonts/fontawesome-webfont.woff2', '[Errno 1] Operation not permitted'), ('/usr/local/web/fonts/sourcesanspro-regular.woff', './html/fonts/sourcesanspro-regular.woff', '[Errno 1] Operation not permitted'), ('/usr/local/web/fonts/sourcesanspro-regularit.woff', './html/fonts/sourcesanspro-regularit.woff', '[Errno 1] Operation not permitted'), ('/usr/local/web/fonts/sourcesanspro-semibold.woff', './html/fonts/sourcesanspro-semibold.woff', '[Errno 1] Operation not permitted'), ('/usr/local/web/fonts/sourcesanspro-semiboldit.woff', './html/fonts/sourcesanspro-semiboldit.woff', '[Errno 1] Operation not permitted'), (, './html/fonts', '[Errno 1] Operation not permitted'), ('/usr/local/web/index.html', './html/index.html', '[Errno 1] Operation not permitted'), ('/usr/local/web/js/ataqv.js', './html/js/ataqv.js', '[Errno 1] Operation not permitted'), ('/usr/local/web/js/d3.min.js', './html/js/d3.min.js', '[Errno 1] Operation not permitted'), ('/usr/local/web/js/datatables.min.js', './html/js/datatables.min.js', '[Errno 1] Operation not permitted'), ('/usr/local/web/js/jszip.min.js', './html/js/jszip.min.js', '[Errno 1] Operation not permitted'), (, './html/js', '[Errno 1] Operation not permitted'), ('/usr/local/web', './html/', '[Errno 1] Operation not permitted')]

Work dir:
  /wins/eyss/NGS/NGS_data/_training_folder/kyung_mok/E61_ATAC_Seq_O_vs_Y_LT_HSC/work/ed/8327b0e1bee6df22e4b993074ed0fb

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

**Comment by JoseEspinosa** [comment]
I'd say that there is a problem with permissions when writing files so maybe ask to your system admin how to fix it.

**Comment by JoseEspinosa** [comment]
Since this issue had no activity in the last 3 weeks I'll close it now. Let us know if you need any further help.

**Comment by kkim111** [comment]
Thank you Jose!
You were right. It was a permission problem.
