### ISSUE TITLE
 AttributeError: module 'matplotlib.cm' has no attribute 'register_cmap'

### ISSUE THREAD

**Issue by kasiabla** [nf-core/atacseq#376]
### Description of the bug

Hello, 
Can you help with this error. It repeats when I try to run this command:
`nextflow run nf-core/atacseq -profile conda --input ./ATAC_samples.csv --outdir ./results --genome GRCh38 --read_length 150 -r 2.1.2`

What is the problem and can you recommend any solution?
Thanks in advance, 
Kasia 

![błąd](https://github.com/user-attachments/assets/a01f1a10-70bb-403c-be52-e4935322bfd5)
```
-[nf-core/atacseq] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_DEEPTOOLS_PLOTFINGERPRINT (WT_REP2)'

Caused by:
  Process `NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_DEEPTOOLS_PLOTFINGERPRINT (WT_REP2)` terminated with an error exit status (1)


Command executed:

  plotFingerprint \
      --skipZeros --numberOfSamples 500000 --labels WT_REP2.mLb.clN \
       \
      --bamfiles WT_REP2.mLb.clN.sorted.bam \
      --plotFile WT_REP2.mLb.clN.plotFingerprint.pdf \
      --outRawCounts WT_REP2.mLb.clN.plotFingerprint.raw.txt \
      --outQualityMetrics WT_REP2.mLb.clN.plotFingerprint.qcmetrics.txt \
      --numberOfProcessors 12

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_DEEPTOOLS_PLOTFINGERPRINT":
      deeptools: $(plotFingerprint --version | sed -e "s/plotFingerprint //g")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/home/kasia/ATAC_seq_Macrogen_2024/work/conda/env-0d01150023c68e439ebff3eb959d98bf/bin/plotFingerprint", line 5, in <module>
      from deeptools.plotFingerprint import main
    File "/home/kasia/ATAC_seq_Macrogen_2024/work/conda/env-0d01150023c68e439ebff3eb959d98bf/lib/python3.11/site-packages/deeptools/plotFingerprint.py", line 11, in <module>
      from deeptools import cm  # noqa: F401
      ^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/kasia/ATAC_seq_Macrogen_2024/work/conda/env-0d01150023c68e439ebff3eb959d98bf/lib/python3.11/site-packages/deeptools/cm.py", line 1087, in <module>
      mpl_cm.register_cmap(_name, _cmap)
      ^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'matplotlib.cm' has no attribute 'register_cmap'

Work dir:
  /home/kasia/ATAC_seq_Macrogen_2024/work/3b/029286d47730c44976924716f4f90a

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

```

**Comment by JoseEspinosa** [comment]
Might be that you have a conflict in your conda environment, see [this](https://stackoverflow.com/questions/78628960/module-matplotlib-cm-has-no-attribute-get-cmap) post. If you could run it using either singularity or docker I will recommend it.

**Comment by kasiabla** [comment]
Thank you Jose, 
Using docker, it worked! 
Great recommendation, 
Cheers, 
Kasia

**Comment by JoseEspinosa** [comment]
Since the issue was fixed, I will close it
