### ISSUE TITLE
ERROR ~ Error executing process > 'NFCORE_ATACSEQ:ATACSEQ:FASTQ_FASTQC_UMITOOLS_TRIMGALORE:TRIMGALORE

### ISSUE THREAD

**Issue by Kermaa** [nf-core/atacseq#377]
### Description of the bug

Hi,

I want to perform NF-core ATAC-seq but I have issues with the trimming for only one sample.. I don't understand what the issue is.. Can you explain to me, please?
<img width="985" alt="Capture d’écran 2024-08-10 à 10 15 04" src="https://github.com/user-attachments/assets/f4424398-51b3-4cea-a54b-c097df2e8f4a">

### Command used and terminal output

```console
nextflow run nf-core/atacseq -profile ifb_core --email marie.kervella@inserm.fr --input /shared/projects/dmd_epi/Data_sequencing/ATAC-seq_samples_files_mouse_new.csv --outdir /shared/projects/dmd_epi/Data_analysis --aligner bowtie2 -work-dir /shared/projects/dmd_epi/work --fasta /shared/bank/mus_musculus/latest_genome/bowtie2/Mus_musculus.GRCm39.dna.toplevel.fa --gtf /shared/bank/mus_musculus/GRCm39/Ensembl_108/gtf/Mus_musculus.GRCm39.108.gtf --bowtie2_index /shared/bank/mus_musculus/GRCm39/bowtie2/ —min_rep_consensus 2 --read_length 50

                                                                           
ERROR ~ Error executing process > 'NFCORE_ATACSEQ:ATACSEQ:FASTQ_FASTQC_UMITOOLS_TRIMGALORE:TRIMGALORE (LMNA_6m_REP1_T1)'

Caused by:
  Process `NFCORE_ATACSEQ:ATACSEQ:FASTQ_FASTQC_UMITOOLS_TRIMGALORE:TRIMGALORE (LMNA_6m_REP1_T1)` terminated with an error exit status (1)


Command executed:

  [ ! -f  LMNA_6m_REP1_T1_1.fastq.gz ] && ln -s mLMNA_6m_Rep2_S99_L006_R1_001.fastq.gz LMNA_6m_REP1_T1_1.fastq.gz
  [ ! -f  LMNA_6m_REP1_T1_2.fastq.gz ] && ln -s mLMNA_6m_Rep2_S99_L006_R2_001.fastq.gz LMNA_6m_REP1_T1_2.fastq.gz
  trim_galore \
      --fastqc \
      --cores 8 \
      --paired \
      --gzip \
      LMNA_6m_REP1_T1_1.fastq.gz \
      LMNA_6m_REP1_T1_2.fastq.gz
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_ATACSEQ:ATACSEQ:FASTQ_FASTQC_UMITOOLS_TRIMGALORE:TRIMGALORE":
      trimgalore: $(echo $(trim_galore --version 2>&1) | sed 's/^.*version //; s/Last.*$//')
      cutadapt: $(cutadapt --version)
  END_VERSIONS

Command exit status:
  1

Command output:
  pigz 2.6

Command error:
  ERROR: Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/cutadapt/pipeline.py", line 559, in run
      for chunk_index, chunk in enumerate(dnaio.read_chunks(f, self.buffer_size)):
    File "/usr/local/lib/python3.9/site-packages/dnaio/chunks.py", line 81, in read_chunks
      bufend = f.readinto(memoryview(buf)[start:]) + start  # type: ignore
    File "/usr/local/lib/python3.9/gzip.py", line 300, in read
      return self._buffer.read(size)
    File "/usr/local/lib/python3.9/_compression.py", line 68, in readinto
      data = self.read(len(byte_view))
    File "/usr/local/lib/python3.9/gzip.py", line 478, in read
      self._read_eof()
    File "/usr/local/lib/python3.9/gzip.py", line 524, in _read_eof
      raise BadGzipFile("CRC check failed %s != %s" % (hex(crc32),
  gzip.BadGzipFile: CRC check failed 0x70d89f70 != 0x202a8444
  
  ERROR: Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/cutadapt/pipeline.py", line 559, in run
      for chunk_index, chunk in enumerate(dnaio.read_chunks(f, self.buffer_size)):
    File "/usr/local/lib/python3.9/site-packages/dnaio/chunks.py", line 81, in read_chunks
      bufend = f.readinto(memoryview(buf)[start:]) + start  # type: ignore
    File "/usr/local/lib/python3.9/gzip.py", line 300, in read
      return self._buffer.read(size)
    File "/usr/local/lib/python3.9/_compression.py", line 68, in readinto
      data = self.read(len(byte_view))
    File "/usr/local/lib/python3.9/gzip.py", line 478, in read
      self._read_eof()
    File "/usr/local/lib/python3.9/gzip.py", line 524, in _read_eof
      raise BadGzipFile("CRC check failed %s != %s" % (hex(crc32),
  gzip.BadGzipFile: CRC check failed 0x70d89f70 != 0x202a8444
  
  ERROR: Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/cutadapt/pipeline.py", line 626, in run
      raise e
  gzip.BadGzipFile: CRC check failed 0x70d89f70 != 0x202a8444
  
  Traceback (most recent call last):
    File "/usr/local/bin/cutadapt", line 10, in <module>
      sys.exit(main_cli())
    File "/usr/local/lib/python3.9/site-packages/cutadapt/__main__.py", line 848, in main_cli
      main(sys.argv[1:])
    File "/usr/local/lib/python3.9/site-packages/cutadapt/__main__.py", line 913, in main
      stats = r.run()
    File "/usr/local/lib/python3.9/site-packages/cutadapt/pipeline.py", line 825, in run
      raise e
  gzip.BadGzipFile: CRC check failed 0x70d89f70 != 0x202a8444
  
  
  Cutadapt terminated with exit signal: '256'.
  Terminating Trim Galore run, please check error message(s) to get an idea what went wrong...

Work dir:
  /shared/projects/dmd_epi/work/9b/510318e2d1bbbaaa7ca764a6a00c46

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
```

**Comment by yushuen** [comment]
Hi, I got similar error messages before. Finally, I found it is about data loss during transferring.
Have you checked the file integrity?
