### ISSUE TITLE
Picard "--TMP_DIR" arguments are hardcoded

### ISSUE THREAD

**Issue by vondoRishi** [nf-core/atacseq#378]
### Description of the bug

An error "No space left on device" occurred by  process `NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_MARKDUPLICATES_PICARD:PICARD_MARKDUPLICATES (E145I_REP1)`. Possible reason "--TMP_DIR" arguments are hardcoded in modules.config (example https://github.com/nf-core/atacseq/blob/1a1dbe52ffbd82256c941a032b0e22abbd925b8a/conf/modules.config#L358).  

Caused by:
  Process `NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_MARKDUPLICATES_PICARD:PICARD_MARKDUPLICATES (E145I_REP1)` terminated with an error exit status (1)

Command executed:

  ```
picard \
      -Xmx29491M \
      MarkDuplicates \
      --ASSUME_SORTED true --REMOVE_DUPLICATES false --VALIDATION_STRINGENCY LENIENT --TMP_DIR tmp \
      --INPUT E145I_REP1.mLb.sorted.bam \
      --OUTPUT E145I_REP1.mLb.mkD.sorted.bam \
      --REFERENCE_SEQUENCE Mus_musculus.GRCm38.dna.primary_assembly.fa \
      --METRICS_FILE E145I_REP1.mLb.mkD.sorted.MarkDuplicates.metrics.txt
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_MARKDUPLICATES_PICARD:PICARD_MARKDUPLICATES":
      picard: $(echo $(picard MarkDuplicates --version 2>&1) | grep -o 'Version:.*' | cut -f2- -d:)
  END_VERSIONS
```

Command error:

```
Runtime.totalMemory()=4311744512
  To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
  Exception in thread "main" htsjdk.samtools.SAMException: Error loading new map from disk.
        at htsjdk.samtools.CoordinateSortedPairInfoMap.ensureSequenceLoaded(CoordinateSortedPairInfoMap.java:143)
        at htsjdk.samtools.CoordinateSortedPairInfoMap.remove(CoordinateSortedPairInfoMap.java:86)
        at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.remove(DiskBasedReadEndsForMarkDuplicatesMap.java:61)
        at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:560)
        at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:270)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:289)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:104)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:114)
  Caused by: java.io.IOException: No space left on device
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(FileOutputStream.java:349)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
        at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
        at htsjdk.samtools.CoordinateSortedPairInfoMap.ensureSequenceLoaded(CoordinateSortedPairInfoMap.java:119)
```

### Command used and terminal output

```console
Slurm declaration

export TMPDIR=$PWD
export SINGULARITY_TMPDIR=$PWD
export SINGULARITY_CACHEDIR=$PWD
unset XDG_RUNTIME_DIR
```

### System information

- Nextflow version - 24.01.0-edge
- Hardware - HPC
- Executor - slurm
- Container engine: - Singularity
- OS - Linux
- Version of nf-core/atacseq 2.1.2

**Comment by JoseEspinosa** [comment]
Actually, you can overwrite the arguments with a `custom.config` see [here](https://nf-co.re/docs/usage/getting_started/configuration#custom-configuration-files).
You can for instance in this case provide a configuration file like:
```
withName: '.*:MERGED_LIBRARY_MARKDUPLICATES_PICARD:PICARD_MARKDUPLICATES' {
        ext.args   = '--ASSUME_SORTED true --REMOVE_DUPLICATES false --VALIDATION_STRINGENCY LENIENT --TMP_DIR your_path_here'
}
```
