### ISSUE TITLE
Error executing process > 'get_software_versions'

### ISSUE THREAD

**Issue by xbjie123** [nf-core/atacseq#54]
Hi,

I'm running atacseq pipeline. Previous it works well. However, I met a problem that caused by `Process `get_software_versions` terminated with an error exit status (127)`

Could you help me with this issue?

This error does not occur before I install Deseq2 R package. I am not sure if this error is associated with the installation. 

The detailed error information is 
```
ERROR ~ Error executing process > 'get_software_versions'

Caused by:
  Process `get_software_versions` terminated with an error exit status (127)

Command executed:

  echo 1.0.0 > v_pipeline.txt
  echo 19.04.0 > v_nextflow.txt
  fastqc --version > v_fastqc.txt
  trim_galore --version > v_trim_galore.txt
  echo $(bwa 2>&1) > v_bwa.txt
  samtools --version > v_samtools.txt
  bedtools --version > v_bedtools.txt
  echo $(bamtools --version 2>&1) > v_bamtools.txt
  picard MarkDuplicates --version &> v_picard.txt  || true
  echo $(R --version 2>&1) > v_R.txt
  python -c "import pysam; print(pysam.__version__)" > v_pysam.txt
  echo $(macs2 --version 2>&1) > v_macs2.txt
  touch v_homer.txt
  echo $(ataqv --version 2>&1) > v_ataqv.txt
  echo $(featureCounts -v 2>&1) > v_featurecounts.txt
  multiqc --version > v_multiqc.txt
  scrape_software_versions.py &> software_versions_mqc.yaml

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 17: multiqc: command not found

Work dir:
  /home/xubaijie/work/f4/a2d5c0c64a8a599c953ea75b3746e6

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

```

Hope to get your kindly reply.

Best
Baijie

**Comment by drpatelh** [comment]
HI @xbjie123 . This sort of error normally occurs when Nextflow is unable to use the software in the container. Can you send me the full command you are using please? along with any custom configuration files you have created. Thanks!

**Comment by xbjie123** [comment]
Thanks for the quick reply. Here is my full command.
```

nextflow run /home/xubaijie/pipeline/atacseq-master \
--custom_config_base /home/xubaijie/configs/configs-master/ \
--design /home/xubaijie/personaldata/uploaddata/ATAC_P12_P24/design.csv \
--genome GRCz10 --fasta /home/xubaijie/personaldata/uploaddata/ATAC_analysis/reference_ensmbl/Danio_rerio/Ensembl/GRCz10/Sequence/WholeGenomeFasta/genome.fa \
--bwa_index /home/xubaijie/personaldata/uploaddata/ATAC_analysis/reference_ensmbl/Danio_rerio/Ensembl/GRCz10/Sequence/BWAIndex/genome.fa \
--gtf /home/xubaijie/personaldata/uploaddata/ATAC_analysis/reference_ensmbl/Danio_rerio/Ensembl/GRCz10/Annotation/Archives/archive-2015-07-24-14-30-41/Genes/genes.gtf \
--macs_gsize 1.35e9 --mito_name chrM --outdir /home/xubaijie/personaldata/uploaddata/ATAC_analysis/nextflow_P12_P24_1023
```
And the configure files are used the one provided in the pipeline.
```
--custom_config_base 
## Download and unzip the config files
cd /path/to/my/configs
wget https://github.com/nf-core/configs/archive/master.zip
unzip master.zip
```

Best
Baijie

**Comment by drpatelh** [comment]
Hi @xbjie123 . 

You need to specify a `-profile` in order run the pipeline because that will resolve how in which form you obtain and execute the software container e.g. `-profile docker` or `-profile singularity`. Do you have Docker or Singularity installed where you are trying to run the pipeline?

You dont need to provide `--custom_config_base` unless you are running offline and using a custom Institute-specific config profile from [`nf-core/configs`](https://github.com/nf-core/configs). Are you running the pipeline offline?

Can you add the correct `-profile` to the command below and try re-running:
```
nextflow run /home/xubaijie/pipeline/atacseq-master/main.nf \
    --design /home/xubaijie/personaldata/uploaddata/ATAC_P12_P24/design.csv \
    --genome GRCz10 \
    --fasta /home/xubaijie/personaldata/uploaddata/ATAC_analysis/reference_ensmbl/Danio_rerio/Ensembl/GRCz10/Sequence/WholeGenomeFasta/genome.fa \
    --bwa_index /home/xubaijie/personaldata/uploaddata/ATAC_analysis/reference_ensmbl/Danio_rerio/Ensembl/GRCz10/Sequence/BWAIndex/genome.fa \
    --gtf /home/xubaijie/personaldata/uploaddata/ATAC_analysis/reference_ensmbl/Danio_rerio/Ensembl/GRCz10/Annotation/Archives/archive-2015-07-24-14-30-41/Genes/genes.gtf \
    --macs_gsize 1.35e9 \
    --mito_name chrM \
    --outdir /home/xubaijie/personaldata/uploaddata/ATAC_analysis/nextflow_P12_P24_1023
```

**Comment by xbjie123** [comment]
Yes, I'm running the pipeline offline.

In fact, the command works well for one sample before. I said that it didn't work after I install the Deseq2 via conda. So I don't know if this installation change something.

Baijie

**Comment by drpatelh** [comment]
Ok. Cool. Does your institute have a config here on [nf-core/configs](https://github.com/nf-core/configs)? If not, then you dont need to use that parameter.

You shouldnt have to install anything via Conda, you can just use `-profile conda` and the pipeline will create the environment for you automatically but thats going to be a problem because you are running offline :thinking: 

In any case, it would be much better if you could use `Docker` or `Singularity` to run the pipeline? Do you have any of these installed locally? If so, you will need to download the container for offline use. You can use [nf-core/tools download command](https://github.com/nf-core/tools#downloading-pipelines-for-offline-use) for this.

**Comment by xbjie123** [comment]
Dear @drpatelh ,

Sorry for the delayed reply. In fact, I used `conda update -n base` conda and `conda update --all` to update. After that I installed some softwares by conda install.
However, I met another problem when I resolved the previous one.
```
ERROR ~ Error executing process > 'merge_library_ataqv_mkarv'

Caused by:
  Process `merge_library_ataqv_mkarv` terminated with an error exit status (1)

Command executed:

  mkarv --concurrency 6 \
        --force \
        ./html/ \
        r24hpf_R1.ataqv.json r12hpf_R1.ataqv.json r24hpf_R2.ataqv.json r12hpf_R2.ataqv.json r12hpf_R3.ataqv.json r24hpf_R3.ataqv.json

Command exit status:
  1

Command output:
  (empty)

Command error:
  Using 6 concurrent processes to transform ataqv output files
  Copying web visualizer template directory /home/xubaijie/miniconda3/envs/nf-core-atacseq-1.0.0/web to ./html/
  Traceback (most recent call last):
    File "/home/xubaijie/miniconda3/envs/nf-core-atacseq-1.0.0/bin/mkarv", line 596, in <module>
      shutil.copytree(args.template_directory, args.directory)
    File "/home/xubaijie/miniconda3/envs/nf-core-atacseq-1.0.0/lib/python2.7/shutil.py", line 194, in copytree
      names = os.listdir(src)
  OSError: [Errno 2] No such file or directory: '/home/xubaijie/miniconda3/envs/nf-core-atacseq-1.0.0/web'

Work dir:
  /home/xubaijie/work/96/676b0986d94700aa4295761d96a1dc

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```
Do you know how to deal with this?

In fact, my system could not allow me to use `Docker `or `Singularity `to run the pipeline. So I must to go through the whole pipeline with conda. So Hope you could help me to go through this.

Best
Baijie

**Comment by drpatelh** [comment]
Hi @xbjie123 . Sorry, Im still a bit confused as to the environment in which you are trying to run the pipeline. It seems like you are using `conda` to install packages but you said that you are in an offline environment? Are you transferring the `conda` environment somehow?

As I mentioned before, if you can install `conda` packages then you dont need to interact/install with `conda` at all. You just have to use `-profile` conda when running the pipeline and Nextflow will create the `conda` environment for you and run the pipeline using that:
https://www.nextflow.io/docs/latest/conda.html#how-it-works

**Comment by drpatelh** [comment]
Also, it may be worth joining the `atacseq` channel on the `nf-core Slack` workspace 👍 Will be easier to discuss and troubleshoot different options.

**Comment by drpatelh** [comment]
Closing due to inactivity but feel free to reopen if the problem persists.
